name: Avo Inspector

on:
  pull_request:
    types: [opened, reopened, unlocked, synchronize]
    paths:
      - 'src/**'

jobs:
  test:
    name: Test
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build Avo Inspector package
        run: yarn build

      - name: Test Source
        run: |
          yarn test src/ --silent
